services:
  traefik:
    image: traefik
    build:
      context: ./traefik
      dockerfile: ./Dockerfile
    container_name: traefik
    restart: unless-stopped
    environment:
      BASIC_AUTH_CREDENTIALS: "${BASIC_USER}:${BASIC_PASSWORD}"
      HTTPS_PUBLIC_PORT: "8443"
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./traefik/certs/server:/etc/traefik/certs/server:ro
    depends_on:
      garage-ui:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  
  s3-browse:
    build:
        context: ./s3-browse
        dockerfile: ./Dockerfile
    container_name: s3-browse
    restart: unless-stopped
    environment:
        S3_ENDPOINT: "http://garage:3900"
        S3_REGION: "garage"
        S3_ACCESS_KEY_ID: "${KEY_ID}"
        S3_SECRET_ACCESS_KEY: "${KEY_SECRET}"
        S3_BUCKET: "default"
        PORT: "8088"
    ports:
        - 8088:8088
    depends_on:
        garage:
          condition: service_healthy
    healthcheck:
        test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8088/healthz"]
        interval: 10s
        timeout: 3s
        retries: 10
    logging:
        options:
          max-size: "10m"
          max-file: "3"


  garage-ui:
    image: garage-ui
    build:
      context: ./garage-ui
      dockerfile: ./Dockerfile
    container_name: garage-ui
    restart: unless-stopped
    environment:
      API_BASE_URL: http://garage:3903
      S3_ENDPOINT_URL: http://garage:3900
      BASE_PATH: /garage-ui
      ADMIN_TOKEN: "${ADMIN_TOKEN}"
    depends_on:
      garage:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  garage:
    image: garagehq
    build:
      context: ./garage
      dockerfile: ./Dockerfile
    container_name: garage
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      KEY_ID: "${KEY_ID}"
      KEY_SECRET: "${KEY_SECRET}"
      RPC_SECRET: "${RPC_SECRET}"
      ADMIN_TOKEN: "${ADMIN_TOKEN}"
      METRICS_TOKEN: "${METRICS_TOKEN}"
      S3_REGION: garage
      ROOT_DOMAIN: .garage
      USE_LOCAL_TZ: "false"
      REPLICATION_FACTOR: "1"
      COMPRESSION_LEVEL: "0"
    volumes:
      - ./garage/volume/meta:/var/lib/garage/meta:rw
      - ./garage/volume/data:/var/lib/garage/data:rw
    logging:
      options:
        max-size: "10m"
        max-file: "3"
