http:
  routers:
    http-redirect-all:
      entryPoints: ["web"]
      rule: "PathPrefix(`/`)"
      service: "noop@internal"
      middlewares: ["https-only"]

    root-to-garage-ui:
      entryPoints: ["websecure"]
      rule: "Path(`/`)"
      service: garage-ui-svc
      middlewares: ["root-redirect"]
      priority: 1000
      tls: {}

    garage-ui-https:
      entryPoints: ["websecure"]
      rule: "PathPrefix(`/garage-ui`)"
      service: garage-ui-svc
      middlewares: ["garage-ui-add-slash", "secured-basicauth"]
      tls: {}

    traefik-dashboard-https:
      entryPoints: ["websecure"]
      rule: "PathPrefix(`/traefik`)"
      service: "api@internal"
      middlewares: ["traefik-add-slash", "traefik-strip", "secured-basicauth"]
      tls: {}

    traefik-api-scoped-https:
      entryPoints: ["websecure"]
      rule: "PathPrefix(`/api`) && HeaderRegexp(`Referer`, `.*/traefik/.*`)"
      service: "api@internal"
      middlewares: ["secured-basicauth"]
      tls: {}

    garage-s3-router:
      entryPoints: ["websecure"]
      rule: "PathPrefix(`/garage`)"
      service: garage-s3-svc
      middlewares: ["garage-strip"]
      tls:
        options: "mtls@file"

  middlewares:
    garage-ui-add-slash:
      redirectRegex:
        regex: "^/garage-ui$"
        replacement: "/garage-ui/"
        permanent: false

    traefik-add-slash:
      redirectRegex:
        regex: "^/traefik$"
        replacement: "/traefik/"
        permanent: false

    root-redirect:
      redirectRegex:
        regex: "^/*$"
        replacement: "/garage-ui/"
        permanent: true

    traefik-strip:
      stripPrefix:
        prefixes: ["/traefik"]

    garage-strip:
      stripPrefix:
        prefixes: ["/garage"]

    https-only:
      redirectScheme:
        scheme: https
        port: "${HTTPS_PUBLIC_PORT}"
        permanent: false

    secured-basicauth:
      basicAuth:
        usersFile: "/etc/traefik/htpasswd"

  services:
    garage-ui-svc:
      loadBalancer:
        servers:
          - url: "http://garage-ui:3909"

    garage-s3-svc:
      loadBalancer:
        servers:
          - url: "http://garage:3900"

tls:
  certificates:
    - certFile: "/etc/traefik/certs/server/server.crt"
      keyFile: "/etc/traefik/certs/server/server.key"
  options:
    mtls:
      clientAuth:
        caFiles:
          - "/etc/traefik/certs/server/ca.crt"
        clientAuthType: "RequireAndVerifyClientCert"
