global:
  sendAnonymousUsage: false
  checkNewVersion: false

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"
    http3: {}

log:
  level: INFO
  format: json

accessLog: {}

api:
  dashboard: true

ping:
  entryPoint: "web"

providers:
  file:
    filename: "/etc/traefik/dynamic.yaml"
    watch: true
